[build]
  Command = "git clone https://github.com/thelounge/thelounge.git && cd thelounge && yarn install && NODE_ENV=production yarn build && yarn start && node index thelounge start &"
  Publish = "/"